import { stringify } from 'yaml';
import { parseQuizMarkdown } from './parser';
import type { QuizQuestion } from './types';

export const QUIZ_FOLDER = 'Quizzes';

export interface QuizImportPlan {
  folderPath: string;
  filePath: string;
  content: string;
  questionCount: number;
}

const TEMPLATE_QUESTIONS = new Set([
  'Choose the appropriate response to the cause described in the source note.',
  'Name the term described in the source note.',
  // Keep detecting examples copied from prompts generated by earlier releases.
  '参照資料にある用語を答えてください。',
  '参照資料に示された原因から、適切な対処を選んでください。',
]);

function formatError(message: string): Error {
  return new Error(`Check the generated quiz format. ${message}`);
}

function removeSharedIndentation(text: string): string {
  const lines = text.split('\n');
  const indentation = Math.min(...lines.filter((line) => line.trim()).map((line) => /^[ \t]*/.exec(line)![0].length));
  return Number.isFinite(indentation) ? lines.map((line) => line.slice(indentation)).join('\n') : text;
}

/** Strip complete response wrappers, never individual matched fragments. */
function unwrapResponse(markdown: string): string {
  let text = removeSharedIndentation(markdown.replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n')).trim();
  for (;;) {
    const lines = text.split('\n');
    const opening = /^(`{3,}|~{3,})(?:markdown|md|text|plaintext)?[ \t]*$/i.exec(lines[0] ?? '');
    if (!opening || lines.length < 3) return text;
    const marker = opening[1]!;
    const closing = new RegExp(`^[ \\t]*${marker[0]}{${marker.length},}[ \\t]*$`);
    if (!closing.test(lines[lines.length - 1]!)) return text;
    text = removeSharedIndentation(lines.slice(1, -1).join('\n')).trim();
  }
}

/** Every quiz candidate is retained for validation, including incomplete ones. */
function collectDefinitions(markdown: string): string {
  const lines = unwrapResponse(markdown).split('\n');
  const blocks: string[] = [];
  let index = 0;
  while (index < lines.length) {
    const line = lines[index]!;
    const opening = /^[ \t]*(`{3,}|~{3,})([^\r\n]*)$/.exec(line);
    if (opening) {
      const marker = opening[1]!;
      const language = opening[2]!.trim().toLowerCase();
      const start = index++;
      const closing = new RegExp(`^[ \\t]*${marker[0]}{${marker.length},}[ \\t]*$`);
      while (index < lines.length && !closing.test(lines[index]!)) index += 1;
      const body = removeSharedIndentation(lines.slice(start + 1, index).join('\n'));
      if (['note-quiz', 'quiz', 'yaml', 'yml'].includes(language)) {
        if (index === lines.length) throw formatError(`Line ${start + 1}: The quiz code block is not closed.`);
        blocks.push(wrapDefinition(body));
      } else if (/^[ \t]*quiz\s*:/m.test(body)) {
        throw formatError(`Line ${start + 1}: Use quiz as the code block language for questions.`);
      }
      index += 1;
      continue;
    }

    const root = /^([ \t]*)quiz\s*:/.exec(line);
    if (root) {
      const start = index++;
      const indentation = root[1]!.length;
      while (index < lines.length) {
        const next = lines[index]!;
        if (next.trim() && /^[ \t]*/.exec(next)![0].length <= indentation) break;
        index += 1;
      }
      blocks.push(wrapDefinition(removeSharedIndentation(lines.slice(start, index).join('\n'))));
      continue;
    }
    index += 1;
  }
  return blocks.join('\n\n');
}

function wrapDefinition(yaml: string): string {
  // A value may contain Markdown fences; a longer fence keeps them literal.
  const longest = Math.max(2, ...[...yaml.matchAll(/`+/g)].map((match) => match[0].length));
  const fence = '`'.repeat(longest + 1);
  return `${fence}note-quiz\n${yaml.trimEnd()}\n${fence}`;
}

function serializeQuestion(question: QuizQuestion): string {
  const { sourceLine: _sourceLine, ...definition } = question;
  void _sourceLine;
  return wrapDefinition(stringify({ quiz: definition }, { defaultStringType: 'QUOTE_DOUBLE', defaultKeyType: 'PLAIN', lineWidth: 0 }));
}

/** Validate AI output and produce a canonical note containing only real questions. */
export function normalizeGeneratedQuiz(markdown: string): { content: string; questionCount: number } {
  const parsed = parseQuizMarkdown(collectDefinitions(markdown));
  if (parsed.issues.length > 0) {
    throw formatError(parsed.issues.map((issue) => `Line ${issue.line}: ${issue.message}`).join(' / '));
  }
  if (parsed.questions.length === 0) throw new Error('No questions in quiz format were found. Check the AI response.');
  if (parsed.questions.some((question) => TEMPLATE_QUESTIONS.has(question.question))) {
    throw new Error('The response contains prompt examples. Use only questions generated from your source note.');
  }
  return { content: `${parsed.questions.map(serializeQuestion).join('\n\n')}\n`, questionCount: parsed.questions.length };
}

/** Validate Claudian/Copilot clipboard output and choose a collision-free note path. */
export function planClipboardQuizImport(clipboard: string, sourceName: string, existingPaths: ReadonlySet<string>, now = new Date(), outputFolder: string = QUIZ_FOLDER): QuizImportPlan {
  const normalized = normalizeGeneratedQuiz(clipboard);
  const cleanedName = sourceName.replace(/\.md$/i, '').replace(/[\\/:*?"<>|]/g, '_')
    .replace(/\p{Cc}/gu, '_').trim();
  const safeName = [...cleanedName].slice(0, 100).join('').replace(/[. ]+$/, '') || 'quiz';
  const stamp = now.toISOString().replace(/[:.]/g, '-');
  const base = `${outputFolder}/${safeName}-${stamp}`;
  let filePath = `${base}.md`;
  let suffix = 2;
  while (existingPaths.has(filePath)) filePath = `${base}-${suffix++}.md`;
  return { folderPath: outputFolder, filePath, ...normalized };
}
